deck = Deck.create(title: "Salamanders")

deck.cards.create(question: "Alex", answer: "Froelich")
deck.cards.create(question: "Andrew", answer: "Guard")
deck.cards.create(question: "Chirag", answer: "Tailor")
deck.cards.create(question: "Chris", answer: "Wright")
deck.cards.create(question: "Clark", answer: "Kampfe")
deck.cards.create(question: "Clay", answer: "Morton")
deck.cards.create(question: "Connor", answer: "McCrone")
deck.cards.create(question: "Danny", answer: "Lu")
deck.cards.create(question: "Elaine", answer: "Yu")
deck.cards.create(question: "Jake", answer: "Koten")
deck.cards.create(question: "Jane", answer: "Scharankov")
deck.cards.create(question: "Kathryn", answer: "Exline")
deck.cards.create(question: "Kent", answer: "Carmine")
deck.cards.create(question: "Meara", answer: "Charnetzki")
deck.cards.create(question: "Melissa", answer: "Louie")
deck.cards.create(question: "Nathan", answer: "Hadlock")
deck.cards.create(question: "Oliver", answer: "Francescatti")
deck.cards.create(question: "Shawn", answer: "Klein")
deck.cards.create(question: "Tanner", answer: "Hartwig")
deck.cards.create(question: "Tara", answer: "Roys")
deck.cards.create(question: "Tyson", answer: "Kunovsky")
deck.cards.create(question: "Ava", answer: "St. Clair")
deck.cards.create(question: "Diana", answer: "Calvache")
deck.cards.create(question: "Justin", answer: "Park")
deck.cards.create(question: "Pedro", answer: "Coronel")
